import { CartItem, ProductColor, ProductImage, productObj, ProductSpec } from "@/types/product";

export const productList: productObj[] = [
	{
        id: 1,
		name: 'Minimalist Audio Pods',
		category: 'Audio',
		price: 199.0,
		originalPrice: 249.0,
		rating: 4.8,
		reviews: 124,
		inStock: true,
		description:
			'Experience pure sound with active noise cancellation and a transparency mode that lets the world back in. Designed for all-day comfort with a customizable fit.',
		colors: [
			{
				name: 'Pearl White',
				value: 'white',
				bgClass: 'bg-white border border-gray-300 dark:border-gray-600',
			},
			{ name: 'Obsidian Black', value: 'black', bgClass: 'bg-gray-900' },
			{ name: 'Violet', value: 'violet', bgClass: 'bg-violet-500' },
		] as ProductColor[],
		specifications: [
			{ label: 'Battery Life', value: 'Up to 24 hours' },
			{ label: 'Water Resistance', value: 'IPX4 Rated' },
			{ label: 'Connectivity', value: 'Bluetooth 5.3' },
			{ label: 'Charging', value: 'USB-C & Wireless' },
		] as ProductSpec[],
		images: [
			{ id: 0, src: '/globe.svg', alt: 'View 0' },
			{ id: 1, src: '/file.svg', alt: 'View 1' },
			{ id: 2, src: '/window.svg', alt: 'View 2' },
			{ id: 3, src: '/next.svg', alt: 'View 3' },
		] as ProductImage[],
	},
	{
        id: 2,
		name: 'Minimalist Audio Pods',
		category: 'Audio',
		price: 199.0,
		originalPrice: 249.0,
		rating: 4.8,
		reviews: 124,
		inStock: true,
		description:
			'Experience pure sound with active noise cancellation and a transparency mode that lets the world back in. Designed for all-day comfort with a customizable fit.',
		colors: [
			{
				name: 'Pearl White',
				value: 'white',
				bgClass: 'bg-white border border-gray-300 dark:border-gray-600',
			},
			{ name: 'Obsidian Black', value: 'black', bgClass: 'bg-gray-900' },
			{ name: 'Violet', value: 'violet', bgClass: 'bg-violet-500' },
		] as ProductColor[],
		specifications: [
			{ label: 'Battery Life', value: 'Up to 24 hours' },
			{ label: 'Water Resistance', value: 'IPX4 Rated' },
			{ label: 'Connectivity', value: 'Bluetooth 5.3' },
			{ label: 'Charging', value: 'USB-C & Wireless' },
		] as ProductSpec[],
		images: [
			{ id: 0, src: '/globe.svg', alt: 'View 0' },
			{ id: 1, src: '/file.svg', alt: 'View 1' },
			{ id: 2, src: '/window.svg', alt: 'View 2' },
			{ id: 3, src: '/next.svg', alt: 'View 3' },
		] as ProductImage[],
	},
	{
        id: 3,
		name: 'Minimalist Audio Pods',
		category: 'Audio',
		price: 199.0,
		originalPrice: 249.0,
		rating: 4.8,
		reviews: 124,
		inStock: true,
		description:
			'Experience pure sound with active noise cancellation and a transparency mode that lets the world back in. Designed for all-day comfort with a customizable fit.',
		colors: [
			{
				name: 'Pearl White',
				value: 'white',
				bgClass: 'bg-white border border-gray-300 dark:border-gray-600',
			},
			{ name: 'Obsidian Black', value: 'black', bgClass: 'bg-gray-900' },
			{ name: 'Violet', value: 'violet', bgClass: 'bg-violet-500' },
		] as ProductColor[],
		specifications: [
			{ label: 'Battery Life', value: 'Up to 24 hours' },
			{ label: 'Water Resistance', value: 'IPX4 Rated' },
			{ label: 'Connectivity', value: 'Bluetooth 5.3' },
			{ label: 'Charging', value: 'USB-C & Wireless' },
		] as ProductSpec[],
		images: [
			{ id: 0, src: '/globe.svg', alt: 'View 0' },
			{ id: 1, src: '/file.svg', alt: 'View 1' },
			{ id: 2, src: '/window.svg', alt: 'View 2' },
			{ id: 3, src: '/next.svg', alt: 'View 3' },
		] as ProductImage[],
	},
	{
        id: 4,
		name: 'Minimalist Audio Pods',
		category: 'Audio',
		price: 199.0,
		originalPrice: 249.0,
		rating: 4.8,
		reviews: 124,
		inStock: true,
		description:
			'Experience pure sound with active noise cancellation and a transparency mode that lets the world back in. Designed for all-day comfort with a customizable fit.',
		colors: [
			{
				name: 'Pearl White',
				value: 'white',
				bgClass: 'bg-white border border-gray-300 dark:border-gray-600',
			},
			{ name: 'Obsidian Black', value: 'black', bgClass: 'bg-gray-900' },
			{ name: 'Violet', value: 'violet', bgClass: 'bg-violet-500' },
		] as ProductColor[],
		specifications: [
			{ label: 'Battery Life', value: 'Up to 24 hours' },
			{ label: 'Water Resistance', value: 'IPX4 Rated' },
			{ label: 'Connectivity', value: 'Bluetooth 5.3' },
			{ label: 'Charging', value: 'USB-C & Wireless' },
		] as ProductSpec[],
		images: [
			{ id: 0, src: '/globe.svg', alt: 'View 0' },
			{ id: 1, src: '/file.svg', alt: 'View 1' },
			{ id: 2, src: '/window.svg', alt: 'View 2' },
			{ id: 3, src: '/next.svg', alt: 'View 3' },
		] as ProductImage[],
	},
	{
        id: 5,
		name: 'Minimalist Audio Pods',
		category: 'Audio',
		price: 199.0,
		originalPrice: 249.0,
		rating: 4.8,
		reviews: 124,
		inStock: true,
		description:
			'Experience pure sound with active noise cancellation and a transparency mode that lets the world back in. Designed for all-day comfort with a customizable fit.',
		colors: [
			{
				name: 'Pearl White',
				value: 'white',
				bgClass: 'bg-white border border-gray-300 dark:border-gray-600',
			},
			{ name: 'Obsidian Black', value: 'black', bgClass: 'bg-gray-900' },
			{ name: 'Violet', value: 'violet', bgClass: 'bg-violet-500' },
		] as ProductColor[],
		specifications: [
			{ label: 'Battery Life', value: 'Up to 24 hours' },
			{ label: 'Water Resistance', value: 'IPX4 Rated' },
			{ label: 'Connectivity', value: 'Bluetooth 5.3' },
			{ label: 'Charging', value: 'USB-C & Wireless' },
		] as ProductSpec[],
		images: [
			{ id: 0, src: '/globe.svg', alt: 'View 0' },
			{ id: 1, src: '/file.svg', alt: 'View 1' },
			{ id: 2, src: '/window.svg', alt: 'View 2' },
			{ id: 3, src: '/next.svg', alt: 'View 3' },
		] as ProductImage[],
	},
	{
        id: 6,
		name: 'Minimalist Audio Pods',
		category: 'Audio',
		price: 199.0,
		originalPrice: 249.0,
		rating: 4.8,
		reviews: 124,
		inStock: true,
		description:
			'Experience pure sound with active noise cancellation and a transparency mode that lets the world back in. Designed for all-day comfort with a customizable fit.',
		colors: [
			{
				name: 'Pearl White',
				value: 'white',
				bgClass: 'bg-white border border-gray-300 dark:border-gray-600',
			},
			{ name: 'Obsidian Black', value: 'black', bgClass: 'bg-gray-900' },
			{ name: 'Violet', value: 'violet', bgClass: 'bg-violet-500' },
		] as ProductColor[],
		specifications: [
			{ label: 'Battery Life', value: 'Up to 24 hours' },
			{ label: 'Water Resistance', value: 'IPX4 Rated' },
			{ label: 'Connectivity', value: 'Bluetooth 5.3' },
			{ label: 'Charging', value: 'USB-C & Wireless' },
		] as ProductSpec[],
		images: [
			{ id: 0, src: '/globe.svg', alt: 'View 0' },
			{ id: 1, src: '/file.svg', alt: 'View 1' },
			{ id: 2, src: '/window.svg', alt: 'View 2' },
			{ id: 3, src: '/next.svg', alt: 'View 3' },
		] as ProductImage[],
	},
    {
        id: 7,
		name: 'Minimalist Audio Pods',
		category: 'Audio',
		price: 199.0,
		originalPrice: 249.0,
		rating: 4.8,
		reviews: 124,
		inStock: true,
		description:
			'Experience pure sound with active noise cancellation and a transparency mode that lets the world back in. Designed for all-day comfort with a customizable fit.',
		colors: [
			{
				name: 'Pearl White',
				value: 'white',
				bgClass: 'bg-white border border-gray-300 dark:border-gray-600',
			},
			{ name: 'Obsidian Black', value: 'black', bgClass: 'bg-gray-900' },
			{ name: 'Violet', value: 'violet', bgClass: 'bg-violet-500' },
		] as ProductColor[],
		specifications: [
			{ label: 'Battery Life', value: 'Up to 24 hours' },
			{ label: 'Water Resistance', value: 'IPX4 Rated' },
			{ label: 'Connectivity', value: 'Bluetooth 5.3' },
			{ label: 'Charging', value: 'USB-C & Wireless' },
		] as ProductSpec[],
		images: [
			{ id: 0, src: '/globe.svg', alt: 'View 0' },
			{ id: 1, src: '/file.svg', alt: 'View 1' },
			{ id: 2, src: '/window.svg', alt: 'View 2' },
			{ id: 3, src: '/next.svg', alt: 'View 3' },
		] as ProductImage[],
	},
	{
        id: 8,
		name: 'Minimalist Audio Pods',
		category: 'Audio',
		price: 199.0,
		originalPrice: 249.0,
		rating: 4.8,
		reviews: 124,
		inStock: true,
		description:
			'Experience pure sound with active noise cancellation and a transparency mode that lets the world back in. Designed for all-day comfort with a customizable fit.',
		colors: [
			{
				name: 'Pearl White',
				value: 'white',
				bgClass: 'bg-white border border-gray-300 dark:border-gray-600',
			},
			{ name: 'Obsidian Black', value: 'black', bgClass: 'bg-gray-900' },
			{ name: 'Violet', value: 'violet', bgClass: 'bg-violet-500' },
		] as ProductColor[],
		specifications: [
			{ label: 'Battery Life', value: 'Up to 24 hours' },
			{ label: 'Water Resistance', value: 'IPX4 Rated' },
			{ label: 'Connectivity', value: 'Bluetooth 5.3' },
			{ label: 'Charging', value: 'USB-C & Wireless' },
		] as ProductSpec[],
		images: [
			{ id: 0, src: '/globe.svg', alt: 'View 0' },
			{ id: 1, src: '/file.svg', alt: 'View 1' },
			{ id: 2, src: '/window.svg', alt: 'View 2' },
			{ id: 3, src: '/next.svg', alt: 'View 3' },
		] as ProductImage[],
	},
];

// Sample cart data
// export const initialCartItems: CartItem[] = [
// 	{
// 		id: '1',
// 		name: 'Minimalist Audio Pods',
// 		variant: 'Obsidian Black',
// 		price: 199.0,
// 		quantity: 1,
// 		image: '/globe.svg',
// 		inStock: true,
// 	},
// 	{
// 		id: '2',
// 		name: 'Ergonomic Workspace Chair',
// 		variant: 'Graphite Grey',
// 		price: 450.0,
// 		quantity: 1,
// 		image: '/file.svg',
// 		inStock: true,
// 	},
// 	{
// 		id: '3',
// 		name: 'Mechanical Keyboard',
// 		variant: 'Retro White',
// 		price: 145.0,
// 		quantity: 2,
// 		image: '/window.svg',
// 		inStock: true,
// 	},
// 	{
// 		id: '4',
// 		name: 'Mechanical Keyboard',
// 		variant: 'Retro White',
// 		price: 145.0,
// 		quantity: 2,
// 		image: '/window.svg',
// 		inStock: true,
// 	},
// ];
